- name: Runner
  hosts: all
  become: yes
  vars:
    github_owner: 'myles-coleman'
    github_repo: 'learn-ansible'
    runner_token: "{{ lookup('env','RUNNER_TOKEN') }}"
    runner_name: 'ansible-runner'
    runner_work_dir: '_work'

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - jq

    - name: Download runner package
      get_url:
        url: "https://github.com/actions/runner/releases/download/v2.316.0/actions-runner-linux-arm64-2.316.0.tar.gz"
        dest: "/tmp/actions-runner.tar.gz"

    - name: Create a directory for the runner and install
      file:
        path: "/home/{{ ansible_user }}/actions-runner"
        state: directory

    - name: Change permissions of actions-runner directory
      file:
        path: "/home/{{ ansible_user }}/actions-runner"
        mode: '755'
        recurse: yes

    - name: Extract runner package
      unarchive:
        src: "/tmp/actions-runner.tar.gz"
        dest: "/home/{{ ansible_user }}/actions-runner"
        mode: '777'
        remote_src: yes

    - name: Configure runner
      become: no
      command: "./config.sh --url https://github.com/{{ github_owner }}/{{ github_repo}} --token {{ runner_token }} --unattended"
      args:
        chdir: "/home/{{ ansible_user }}/actions-runner"
      when: not runner_status.stat.exists

    - name: Run Runner
      become: no
      command: "./run.sh"
      args:
        chdir: "/home/{{ ansible_user }}/actions-runner"